steps:
# Build the container for price
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/price', '.']
  dir: 'microservices/price'
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/price']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'price', '--image', 'gcr.io/$PROJECT_ID/price', '--region', '$_REGION','--vpc-connector','vpc-connector','--vpc-egress','all','--update-env-vars','mongohost=10.132.0.58,mongoport=27017,MONGO_USERNAME=appuser,MONGO_PASSWORD=apppwd']
images:
- gcr.io/$PROJECT_ID/price
